name: Codespaces Prebuilds

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prebuild:
    name: Create Codespaces Prebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Codespaces Prebuild
        uses: github/codespaces-precreate@v1
        with:
          devcontainer-path: .devcontainer/devcontainer.json
          prebuild-label: standard