version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    network_mode: service:postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mailchats
      - NODE_ENV=development
      - PORT=3000
      - SESSION_SECRET=dev_session_secret
      
  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mailchats
    ports:
      - 5432:5432

volumes:
  postgres-data: