name: Validate Codespaces Configuration

on:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.devcontainer/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate devcontainer.json
        run: |
          if ! jq empty .devcontainer/devcontainer.json; then
            echo "devcontainer.json is not valid JSON"
            exit 1
          fi
          echo "devcontainer.json is valid JSON"
          
      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin docker-compose
          echo "Docker Compose V2 version:"
          docker compose version || echo "Docker Compose V2 not available"
          echo "Docker Compose V1 version:"
          docker-compose --version || echo "Docker Compose V1 not available"
          
      - name: Validate docker-compose.yml
        run: |
          cd .devcontainer
          # Try Docker Compose V2 first, fall back to V1 if needed
          docker compose config || docker-compose config
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Test Dockerfile build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max